INSERT INTO competicoes (nome, regiao, tipo, linktransfermarket, ehselecaonacional)
SELECT nome, regiao, tipo, linktransfermarket, ehselecaonacional FROM (VALUES
  ('Serie B',               'Brasil', 'PONTOS_CORRIDOS', 'apifoot:72:2026',   false),
  ('Serie C',               'Brasil', 'PONTOS_CORRIDOS', 'apifoot:75:2026',   false),
  ('Serie D',               'Brasil', 'PONTOS_CORRIDOS', 'apifoot:76:2026',   false),
  ('Brasileiro Women',      'Brasil', 'PONTOS_CORRIDOS', 'apifoot:74:2026',   false),
  ('Supercopa do Brasil',   'Brasil', 'MATA_MATA',       'apifoot:632:2026',  false),
  ('Paulista - A1',         'Brasil', 'PONTOS_CORRIDOS', 'apifoot:475:2026',  false),
  ('Paulista - A2',         'Brasil', 'PONTOS_CORRIDOS', 'apifoot:476:2026',  false),
  ('Paulista - A3',         'Brasil', 'PONTOS_CORRIDOS', 'apifoot:605:2026',  false),
  ('Paulista - A4',         'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1062:2026', false),
  ('Copa Paulista',         'Brasil', 'MATA_MATA',       'apifoot:742:2026',  false),
  ('Gaucho - 1',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:477:2026',  false),
  ('Copa Gaucha',           'Brasil', 'MATA_MATA',       'apifoot:1158:2026', false),
  ('Carioca - 1',           'Brasil', 'PONTOS_CORRIDOS', 'apifoot:624:2026',  false),
  ('Carioca A2',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:851:2026',  false),
  ('Carioca C',             'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1106:2026', false),
  ('Mineiro - 1',           'Brasil', 'PONTOS_CORRIDOS', 'apifoot:629:2026',  false),
  ('Mineiro - 2',           'Brasil', 'PONTOS_CORRIDOS', 'apifoot:619:2026',  false),
  ('Catarinense - 1',       'Brasil', 'PONTOS_CORRIDOS', 'apifoot:604:2026',  false),
  ('Catarinense - 2',       'Brasil', 'PONTOS_CORRIDOS', 'apifoot:936:2026',  false),
  ('Recopa Catarinense',    'Brasil', 'MATA_MATA',       'apifoot:1059:2026', false),
  ('Paranaense - 1',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:606:2026',  false),
  ('Paranaense - 2',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:614:2026',  false),
  ('Paranaense - 3',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1138:2026', false),
  ('Baiano - 1',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:602:2026',  false),
  ('Baiano - 2',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:613:2026',  false),
  ('Cearense - 1',          'Brasil', 'PONTOS_CORRIDOS', 'apifoot:609:2026',  false),
  ('Cearense - 2',          'Brasil', 'PONTOS_CORRIDOS', 'apifoot:620:2026',  false),
  ('Pernambucano - 1',      'Brasil', 'PONTOS_CORRIDOS', 'apifoot:622:2026',  false),
  ('Goiano - 1',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:628:2026',  false),
  ('Potiguar',              'Brasil', 'PONTOS_CORRIDOS', 'apifoot:616:2026',  false),
  ('Paraibano',             'Brasil', 'PONTOS_CORRIDOS', 'apifoot:603:2026',  false),
  ('Paraense',              'Brasil', 'PONTOS_CORRIDOS', 'apifoot:627:2026',  false),
  ('Piauiense',             'Brasil', 'PONTOS_CORRIDOS', 'apifoot:621:2026',  false),
  ('Sergipano',             'Brasil', 'PONTOS_CORRIDOS', 'apifoot:626:2026',  false),
  ('Maranhense',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:608:2026',  false),
  ('Maranhense - 2',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1148:2026', false),
  ('Amazonense',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:522:2026',  false),
  ('Acreano',               'Brasil', 'PONTOS_CORRIDOS', 'apifoot:520:2026',  false),
  ('Capixaba',              'Brasil', 'PONTOS_CORRIDOS', 'apifoot:611:2026',  false),
  ('Capixaba B',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1147:2026', false),
  ('Copa Espirito Santo',   'Brasil', 'MATA_MATA',       'apifoot:1097:2026', false),
  ('Tocantinense',          'Brasil', 'PONTOS_CORRIDOS', 'apifoot:631:2026',  false),
  ('Rondoniense',           'Brasil', 'PONTOS_CORRIDOS', 'apifoot:615:2026',  false),
  ('Sul-Matogrossense',     'Brasil', 'PONTOS_CORRIDOS', 'apifoot:623:2026',  false),
  ('Matogrossense',         'Brasil', 'PONTOS_CORRIDOS', 'apifoot:630:2026',  false),
  ('Matogrossense 2',       'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1096:2026', false),
  ('Amapaense',             'Brasil', 'PONTOS_CORRIDOS', 'apifoot:521:2026',  false),
  ('Roraimense',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:607:2026',  false),
  ('Brasiliense',           'Brasil', 'PONTOS_CORRIDOS', 'apifoot:610:2026',  false),
  ('Alagoano',              'Brasil', 'MATA_MATA',       'apifoot:77:2026',   false),
  ('Alagoano - 2',          'Brasil', 'MATA_MATA',       'apifoot:1146:2026', false),
  ('Copa Alagoas',          'Brasil', 'MATA_MATA',       'apifoot:1063:2026', false),
  ('Copa do Nordeste',      'Brasil', 'MATA_MATA',       'apifoot:612:2026',  false),
  ('Copa Norte',            'Brasil', 'MATA_MATA',       'apifoot:1223:2026', false),
  ('Copa Sul-Sudeste',      'Brasil', 'MATA_MATA',       'apifoot:1224:2026', false),
  ('Copa Centro-Oeste',     'Brasil', 'MATA_MATA',       'apifoot:1225:2026', false),
  ('Copa Grao Para',        'Brasil', 'MATA_MATA',       'apifoot:1184:2026', false),
  ('Sao Paulo Youth Cup',   'Brasil', 'MATA_MATA',       'apifoot:618:2026',  false),
  ('Brasileiro U20 A',      'Brasil', 'MATA_MATA',       'apifoot:740:2026',  false),
  ('Brasileiro U20 B',      'Brasil', 'MATA_MATA',       'apifoot:1183:2026', false),
  ('Brasileiro U17',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1128:2026', false),
  ('Copa do Brasil U17',    'Brasil', 'MATA_MATA',       'apifoot:1179:2026', false),
  ('Paulista - U20',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1086:2026', false),
  ('Paulista Serie B',      'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1098:2026', false),
  ('Copa Rio U20',          'Brasil', 'MATA_MATA',       'apifoot:1082:2026', false),
  ('Mineiro U20',           'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1107:2026', false),
  ('Catarinense U20',       'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1076:2026', false),
  ('Paranaense U20',        'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1071:2026', false),
  ('Baiano U20',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1073:2026', false),
  ('Cearense U20',          'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1112:2026', false),
  ('Goiano U20',            'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1069:2026', false),
  ('Brasiliense U20',       'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1100:2026', false),
  ('Paraibano U20',         'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1120:2026', false),
  ('Estadual Junior U20',   'Brasil', 'PONTOS_CORRIDOS', 'apifoot:1143:2026', false)
) AS v(nome, regiao, tipo, linktransfermarket, ehselecaonacional)
WHERE NOT EXISTS (
  SELECT 1 FROM competicoes c WHERE c.linktransfermarket = v.linktransfermarket
);
