namespace ControleFutebolWeb.Helpers;

/// <summary>
/// Mapa centralizado de traduções e variantes de nomes de países/seleções.
/// Usado por ApiFootballService, BrasileiraoController e AdminController.
/// </summary>
public static class CountryHelper
{
    private static readonly Dictionary<string, string> _mapa =
        new(StringComparer.OrdinalIgnoreCase)
    {
        // ── CONMEBOL ─────────────────────────────────────────────────────────
        ["Brazil"]                              = "Brasil",
        ["brasil"]                              = "Brasil",
        ["Argentina"]                           = "Argentina",
        ["Uruguay"]                             = "Uruguai",
        ["uruguai"]                             = "Uruguai",
        ["Colombia"]                            = "Colômbia",
        ["colômbia"]                            = "Colômbia",
        ["colombia"]                            = "Colômbia",
        ["Chile"]                               = "Chile",
        ["Paraguay"]                            = "Paraguai",
        ["paraguai"]                            = "Paraguai",
        ["Peru"]                                = "Peru",
        ["Bolivia"]                             = "Bolívia",
        ["bolívia"]                             = "Bolívia",
        ["Venezuela"]                           = "Venezuela",
        ["Ecuador"]                             = "Equador",
        ["equador"]                             = "Equador",

        // ── CONCACAF ─────────────────────────────────────────────────────────
        ["United States"]                       = "Estados Unidos",
        ["USA"]                                 = "Estados Unidos",
        ["estados unidos"]                      = "Estados Unidos",
        ["Canada"]                              = "Canadá",
        ["canadá"]                              = "Canadá",
        ["canada"]                              = "Canadá",
        ["Mexico"]                              = "México",
        ["méxico"]                              = "México",
        ["mexico"]                              = "México",
        ["Panama"]                              = "Panamá",
        ["panamá"]                              = "Panamá",
        ["panama"]                              = "Panamá",
        ["Honduras"]                            = "Honduras",
        ["Jamaica"]                             = "Jamaica",
        ["Costa Rica"]                          = "Costa Rica",

        // ── UEFA ─────────────────────────────────────────────────────────────
        ["Germany"]                             = "Alemanha",
        ["alemanha"]                            = "Alemanha",
        ["deutschland"]                         = "Alemanha",
        ["France"]                              = "França",
        ["França"]                              = "França",
        ["france"]                              = "França",
        ["Spain"]                               = "Espanha",
        ["espanha"]                             = "Espanha",
        ["españa"]                              = "Espanha",
        ["Italy"]                               = "Itália",
        ["England"]                             = "Inglaterra",
        ["inglaterra"]                          = "Inglaterra",
        ["england"]                             = "Inglaterra",
        ["Portugal"]                            = "Portugal",
        ["Netherlands"]                         = "Holanda",
        ["holanda"]                             = "Holanda",
        ["países baixos"]                       = "Holanda",
        ["Belgium"]                             = "Bélgica",
        ["bélgica"]                             = "Bélgica",
        ["belgica"]                             = "Bélgica",
        ["belgium"]                             = "Bélgica",
        ["Switzerland"]                         = "Suíça",
        ["suíça"]                               = "Suíça",
        ["suiça"]                               = "Suíça",
        ["Croatia"]                             = "Croácia",
        ["croácia"]                             = "Croácia",
        ["Denmark"]                             = "Dinamarca",
        ["dinamarca"]                           = "Dinamarca",
        ["Sweden"]                              = "Suécia",
        ["Norway"]                              = "Noruega",
        ["Poland"]                              = "Polônia",
        ["polônia"]                             = "Polônia",
        ["polonia"]                             = "Polônia",
        ["polónia"]                             = "Polônia",
        ["Czech Republic"]                      = "República Checa",
        ["Czechia"]                             = "República Checa",
        ["república checa"]                     = "República Checa",
        ["rep. tcheca"]                         = "República Checa",
        ["Slovakia"]                            = "Eslováquia",
        ["eslováquia"]                          = "Eslováquia",
        ["Slovenia"]                            = "Eslovênia",
        ["eslovênia"]                           = "Eslovênia",
        ["Hungary"]                             = "Hungria",
        ["hungria"]                             = "Hungria",
        ["Romania"]                             = "Romênia",
        ["romênia"]                             = "Romênia",
        ["Serbia"]                              = "Sérvia",
        ["sérvia"]                              = "Sérvia",
        ["Ukraine"]                             = "Ucrânia",
        ["ucrânia"]                             = "Ucrânia",
        ["Austria"]                             = "Áustria",
        ["áustria"]                             = "Áustria",
        ["Greece"]                              = "Grécia",
        ["Turkey"]                              = "Turquia",
        ["Türkiye"]                             = "Turquia",
        ["Turkiye"]                             = "Turquia",
        ["turquia"]                             = "Turquia",
        ["turkey"]                              = "Turquia",
        ["türkiye"]                             = "Turquia",
        ["Russia"]                              = "Rússia",
        ["Scotland"]                            = "Escócia",
        ["escócia"]                             = "Escócia",
        ["scotland"]                            = "Escócia",
        ["Wales"]                               = "País de Gales",
        ["Ireland"]                             = "Irlanda",
        ["Northern Ireland"]                    = "Irlanda do Norte",
        ["Albania"]                             = "Albânia",
        ["albânia"]                             = "Albânia",
        ["Georgia"]                             = "Geórgia",
        ["geórgia"]                             = "Geórgia",

        // ── CAF ──────────────────────────────────────────────────────────────
        ["South Africa"]                        = "África do Sul",
        ["áfrica do sul"]                       = "África do Sul",
        ["Egypt"]                               = "Egito",
        ["egito"]                               = "Egito",
        ["Morocco"]                             = "Marrocos",
        ["marrocos"]                            = "Marrocos",
        ["Nigeria"]                             = "Nigéria",
        ["nigéria"]                             = "Nigéria",
        ["nigeria"]                             = "Nigéria",
        ["Cameroon"]                            = "Camarões",
        ["camarões"]                            = "Camarões",
        ["Ivory Coast"]                         = "Costa do Marfim",
        ["Côte d'Ivoire"]                       = "Costa do Marfim",
        ["Cote d'Ivoire"]                       = "Costa do Marfim",
        ["costa do marfim"]                     = "Costa do Marfim",
        ["Senegal"]                             = "Senegal",
        ["Ghana"]                               = "Gana",
        ["Algeria"]                             = "Argélia",
        ["argélia"]                             = "Argélia",
        ["algeria"]                             = "Argélia",
        ["Tunisia"]                             = "Tunísia",
        ["Mali"]                                = "Mali",
        ["DR Congo"]                            = "República Democrática do Congo",
        ["Democratic Republic of the Congo"]    = "República Democrática do Congo",
        ["república democrática do congo"]      = "República Democrática do Congo",
        ["rd do congo"]                         = "República Democrática do Congo",
        ["rdc"]                                 = "República Democrática do Congo",
        ["Zambia"]                              = "Zâmbia",
        ["Zimbabwe"]                            = "Zimbábue",
        ["Uganda"]                              = "Uganda",
        ["Tanzania"]                            = "Tanzânia",
        ["Kenya"]                               = "Quênia",
        ["Ethiopia"]                            = "Etiópia",
        ["Angola"]                              = "Angola",
        ["Mozambique"]                          = "Moçambique",
        ["Cape Verde"]                          = "Cabo Verde",
        ["Cape Verde Islands"]                  = "Cabo Verde",

        // ── AFC ──────────────────────────────────────────────────────────────
        ["Japan"]                               = "Japão",
        ["japão"]                               = "Japão",
        ["South Korea"]                         = "Coreia do Sul",
        ["Korea Republic"]                      = "Coreia do Sul",
        ["coreia do sul"]                       = "Coreia do Sul",
        ["China"]                               = "China",
        ["Australia"]                           = "Austrália",
        ["austrália"]                           = "Austrália",
        ["New Zealand"]                         = "Nova Zelândia",
        ["Saudi Arabia"]                        = "Arábia Saudita",
        ["arábia saudita"]                      = "Arábia Saudita",
        ["Iran"]                                = "Irã",
        ["irã"]                                 = "Irã",
        ["Iraq"]                                = "Iraque",
        ["Qatar"]                               = "Qatar",
        ["catar"]                               = "Qatar",
        ["qatar"]                               = "Qatar",
        ["United Arab Emirates"]                = "Emirados Árabes",
        ["UAE"]                                 = "Emirados Árabes",
        ["Israel"]                              = "Israel",
        ["Jordan"]                              = "Jordânia",
        ["Uzbekistan"]                          = "Uzbequistão",
        ["uzbequistão"]                         = "Uzbequistão",
        ["Indonesia"]                           = "Indonésia",
        ["indonésia"]                           = "Indonésia",

        // ── CONCACAF extra ───────────────────────────────────────────────────
        ["Curacao"]                             = "Curaçao",
        ["Curaçao"]                             = "Curaçao",
        ["Haiti"]                               = "Haiti",
        ["Suriname"]                            = "Suriname",
        ["New Caledonia"]                       = "Nova Caledônia",
        ["Trinidad and Tobago"]                 = "Trinidad e Tobago",
        ["Trinidad & Tobago"]                   = "Trinidad e Tobago",
        ["El Salvador"]                         = "El Salvador",
        ["Guatemala"]                           = "Guatemala",
        ["Nicaragua"]                           = "Nicarágua",
        ["Cuba"]                                = "Cuba",
        ["Dominican Republic"]                  = "República Dominicana",
        ["Puerto Rico"]                         = "Porto Rico",
        ["Grenada"]                             = "Granada",
        ["Bermuda"]                             = "Bermudas",
        ["Guyana"]                              = "Guiana",
        ["French Guiana"]                       = "Guiana Francesa",
        ["Martinique"]                          = "Martinica",
        ["Guadeloupe"]                          = "Guadalupe",

        // ── UEFA extra (nacionalidades comuns em elencos de clube) ───────────
        ["Bosnia and Herzegovina"]              = "Bósnia e Herzegovina",
        ["Bosnia & Herzegovina"]                = "Bósnia e Herzegovina",
        ["bósnia e herzegovina"]                = "Bósnia e Herzegovina",
        ["Bósnia"]                              = "Bósnia e Herzegovina",
        ["Bósnia-Herzgovina"]                   = "Bósnia e Herzegovina",
        ["Bósnia-Herzegovina"]                  = "Bósnia e Herzegovina",
        ["Chéquia"]                             = "República Checa",
        ["Kosovo"]                              = "Kosovo",
        ["Montenegro"]                          = "Montenegro",
        ["North Macedonia"]                     = "Macedônia do Norte",
        ["Macedonia"]                           = "Macedônia do Norte",
        ["FYR Macedonia"]                       = "Macedônia do Norte",
        ["Finland"]                             = "Finlândia",
        ["finlândia"]                           = "Finlândia",
        ["Iceland"]                             = "Islândia",
        ["islândia"]                            = "Islândia",
        ["Bulgaria"]                            = "Bulgária",
        ["bulgária"]                            = "Bulgária",
        ["Luxembourg"]                          = "Luxemburgo",
        ["Cyprus"]                              = "Chipre",
        ["Armenia"]                             = "Armênia",
        ["Azerbaijan"]                          = "Azerbaijão",
        ["Belarus"]                             = "Bielorrússia",
        ["Estonia"]                             = "Estônia",
        ["Latvia"]                              = "Letônia",
        ["Lithuania"]                           = "Lituânia",
        ["Moldova"]                             = "Moldávia",
        ["Kazakhstan"]                          = "Cazaquistão",
        ["Malta"]                               = "Malta",

        // ── CAF extra ────────────────────────────────────────────────────────
        ["Guinea"]                              = "Guiné",
        ["guiné"]                               = "Guiné",
        ["Guinea-Bissau"]                       = "Guiné-Bissau",
        ["Equatorial Guinea"]                   = "Guiné Equatorial",
        ["Burkina Faso"]                        = "Burkina Faso",
        ["Gabon"]                               = "Gabão",
        ["gabão"]                               = "Gabão",
        ["Congo"]                               = "Congo",
        ["Benin"]                               = "Benin",
        ["Togo"]                                = "Togo",
        ["Gambia"]                              = "Gâmbia",
        ["Sierra Leone"]                        = "Serra Leoa",
        ["Liberia"]                             = "Libéria",
        ["Madagascar"]                          = "Madagascar",
        ["Mauritania"]                          = "Mauritânia",
        ["Libya"]                               = "Líbia",
        ["Sudan"]                               = "Sudão",
        ["Comoros"]                             = "Comores",
        ["Burundi"]                             = "Burundi",
        ["Niger"]                               = "Níger",
        ["Chad"]                                = "Chade",
        ["Malawi"]                              = "Malaui",
        ["Botswana"]                            = "Botsuana",
        ["Namibia"]                             = "Namíbia",

        // ── AFC extra ────────────────────────────────────────────────────────
        ["Philippines"]                         = "Filipinas",
        ["Thailand"]                            = "Tailândia",
        ["Vietnam"]                             = "Vietnã",
        ["India"]                               = "Índia",
        ["Lebanon"]                             = "Líbano",
        ["Syria"]                               = "Síria",
        ["Palestine"]                           = "Palestina",
        ["Bahrain"]                             = "Bahrein",
        ["Kuwait"]                              = "Kuwait",
        ["Oman"]                                = "Omã",
        ["Yemen"]                               = "Iêmen",
        ["Tajikistan"]                          = "Tadjiquistão",
        ["Kyrgyzstan"]                          = "Quirguistão",
        ["Turkmenistan"]                        = "Turcomenistão",
        ["Afghanistan"]                         = "Afeganistão",
        ["Pakistan"]                            = "Paquistão",
        ["Malaysia"]                            = "Malásia",
        ["Singapore"]                           = "Singapura",
        ["Hong Kong"]                           = "Hong Kong",
        ["Chinese Taipei"]                      = "Taiwan",
        ["Taiwan"]                              = "Taiwan",
        ["North Korea"]                         = "Coreia do Norte",
        ["Korea DPR"]                           = "Coreia do Norte",

        // ── OFC extra ────────────────────────────────────────────────────────
        ["Fiji"]                                = "Fiji",
        ["Papua New Guinea"]                    = "Papua-Nova Guiné",
        ["Tahiti"]                              = "Taiti",

        // ── Variantes em alemão (Transfermarkt) ──────────────────────────────
        ["Bolivien"]                            = "Bolívia",
        ["Kolumbien"]                           = "Colômbia",
        ["Spanien"]                             = "Espanha",
        ["Frankreich"]                          = "França",
        ["Deutschland"]                         = "Alemanha",
        ["Italien"]                             = "Itália",
        ["Niederlande"]                         = "Holanda",
        ["Belgien"]                             = "Bélgica",
        ["Schweiz"]                             = "Suíça",
        ["Kroatien"]                            = "Croácia",
        ["Mexiko"]                              = "México",
        ["Kanada"]                              = "Canadá",
        ["Marokko"]                             = "Marrocos",
        ["Kamerun"]                             = "Camarões",
        ["Serbien"]                             = "Sérvia",
        ["Dänemark"]                            = "Dinamarca",
        ["Griechenland"]                        = "Grécia",
        ["Österreich"]                          = "Áustria",
        ["Türkei"]                              = "Turquia",
        ["Polen"]                               = "Polônia",
        ["Tschechien"]                          = "República Checa",
        ["Ungarn"]                              = "Hungria",
        ["Rumänien"]                            = "Romênia",
        ["Russland"]                            = "Rússia",
        ["Schottland"]                          = "Escócia",
        ["Irland"]                              = "Irlanda",
        ["Nordirland"]                          = "Irlanda do Norte",
        ["Norwegen"]                            = "Noruega",
        ["Schweden"]                            = "Suécia",
        ["Ägypten"]                             = "Egito",
        ["Algerien"]                            = "Argélia",
        ["Tunesien"]                            = "Tunísia",
        ["Elfenbeinküste"]                      = "Costa do Marfim",
        ["Südafrika"]                           = "África do Sul",
        ["Japan"]                               = "Japão",
        ["Südkorea"]                            = "Coreia do Sul",
        ["Australien"]                          = "Austrália",
        ["Neuseeland"]                          = "Nova Zelândia",
        ["Saudi-Arabien"]                       = "Arábia Saudita",
        ["Katar"]                               = "Qatar",

        // ── Variantes extras (football-data / Transfermarkt) ─────────────────
        ["Democratic Republic of Congo"]        = "República Democrática do Congo",
        ["Congo DR"]                            = "República Democrática do Congo",
        ["Rep. Dem. do Congo"]                  = "República Democrática do Congo",
    };

    /// <summary>
    /// Traduz um nome de país em inglês (ou variante) para português.
    /// Retorna o próprio valor se não encontrar mapeamento.
    /// </summary>
    public static string Traduzir(string nome)
    {
        if (string.IsNullOrWhiteSpace(nome)) return nome;
        return _mapa.TryGetValue(nome.Trim(), out var traduzido) ? traduzido : nome;
    }

    /// <summary>
    /// Tenta traduzir, retornando null se não encontrar mapeamento.
    /// </summary>
    public static string? TraduzirOuNull(string nome) =>
        _mapa.TryGetValue(nome?.Trim() ?? "", out var traduzido) ? traduzido : null;
}
