// <auto-generated />
using System;
using ControleFutebolWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFutebolWeb.Migrations
{
    [DbContext(typeof(FutebolContext))]
    [Migration("20260417022128_addCompetitionad")]
    partial class addCompetitionad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("ControleFutebolWeb.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("cartoes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Competicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regiao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("competicoes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datanascimento");

                    b.Property<int?>("NacionalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("nacionalidadeid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("NumeroCamisa")
                        .HasColumnType("integer")
                        .HasColumnName("numerocamisa");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posicao");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.HasKey("Id");

                    b.HasIndex("NacionalidadeId");

                    b.HasIndex("TimeId");

                    b.ToTable("jogadores");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CompeticaoId")
                        .HasColumnType("integer")
                        .HasColumnName("competicaoid");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<int?>("FormacaoCasaId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaocasaid");

                    b.Property<int?>("FormacaoVisitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaovisitanteid");

                    b.Property<string>("Grupo")
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<int>("PartidaApiId")
                        .HasColumnType("integer")
                        .HasColumnName("partidaapiid");

                    b.Property<int>("PlacarCasa")
                        .HasColumnType("integer")
                        .HasColumnName("placarcasa");

                    b.Property<int>("PlacarVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("placarvisitante");

                    b.Property<int>("Rodada")
                        .HasColumnType("integer")
                        .HasColumnName("rodada");

                    b.Property<int>("TimeCasaId")
                        .HasColumnType("integer")
                        .HasColumnName("timecasaid");

                    b.Property<int>("TimeVisitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("timevisitanteid");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("FormacaoCasaId");

                    b.HasIndex("FormacaoVisitanteId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("jogos");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text")
                        .HasColumnName("backgroundurl");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("CorPrincipal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corprincipal");

                    b.Property<string>("CorSecundaria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corsecundaria");

                    b.Property<string>("EscudoUrl")
                        .HasColumnType("text")
                        .HasColumnName("escudourl");

                    b.Property<int>("IdApi")
                        .HasColumnType("integer")
                        .HasColumnName("idapi");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("times");
                });

            modelBuilder.Entity("Escalacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTimeCasa")
                        .HasColumnType("boolean")
                        .HasColumnName("istimecasa");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posicao");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaox");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaoy");

                    b.Property<bool>("Titular")
                        .HasColumnType("boolean")
                        .HasColumnName("titular");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("escalacoes");
                });

            modelBuilder.Entity("Formacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("formacoes");
                });

            modelBuilder.Entity("Gol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("Contra")
                        .HasColumnType("boolean")
                        .HasColumnName("contra");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("gols");
                });

            modelBuilder.Entity("Nacionalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("nacionalidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Argentina"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "França"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Alemanha"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Itália"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Espanha"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Portugal"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Uruguai"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Chile"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Paraguai"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Bolívia"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Peru"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Equador"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Colômbia"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Venezuela"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Guiana"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Suriname"
                        });
                });

            modelBuilder.Entity("PosicaoFormacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("FormacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaoid");

                    b.Property<string>("NomePosicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeposicao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaox");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaoy");

                    b.HasKey("Id");

                    b.HasIndex("FormacaoId");

                    b.ToTable("posicoesformacao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Cartao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany("Cartoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogador", b =>
                {
                    b.HasOne("Nacionalidade", "Nacionalidade")
                        .WithMany("Jogadores")
                        .HasForeignKey("NacionalidadeId");

                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nacionalidade");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogo", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Competicao", null)
                        .WithMany("Jogos")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Formacao", "FormacaoCasa")
                        .WithMany()
                        .HasForeignKey("FormacaoCasaId");

                    b.HasOne("Formacao", "FormacaoVisitante")
                        .WithMany()
                        .HasForeignKey("FormacaoVisitanteId");

                    b.HasOne("ControleFutebolWeb.Models.Time", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Time", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormacaoCasa");

                    b.Navigation("FormacaoVisitante");

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeVisitante");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Nota", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Escalacao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany("Escalacoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Gol", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany("Gols")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("PosicaoFormacao", b =>
                {
                    b.HasOne("Formacao", "Formacao")
                        .WithMany("Posicoes")
                        .HasForeignKey("FormacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formacao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Competicao", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogo", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Escalacoes");

                    b.Navigation("Gols");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Time", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Formacao", b =>
                {
                    b.Navigation("Posicoes");
                });

            modelBuilder.Entity("Nacionalidade", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
