// <auto-generated />
using System;
using ControleFutebolWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFutebolWeb.Migrations
{
    [DbContext(typeof(FutebolContext))]
    partial class FutebolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("ControleFutebolWeb.Models.AnotacaoTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime?>("DtAlt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtalt");

                    b.Property<DateTime>("DtInc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinc");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("anotacoestime");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("accessfailedcount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("emailconfirmed");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("isadmin");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockoutenabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockoutend");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedemail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedusername");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phonenumberconfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("securitystamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("twofactorenabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Assistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("assistencias", (string)null);
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int?>("JogoId1")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid1");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.HasIndex("JogoId1");

                    b.ToTable("cartoes", (string)null);
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Competicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhSelecaoNacional")
                        .HasColumnType("boolean")
                        .HasColumnName("ehselecaonacional");

                    b.Property<int?>("IdApi")
                        .HasColumnType("integer")
                        .HasColumnName("idapi");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logourl");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regiao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<bool>("TopTier")
                        .HasColumnType("boolean")
                        .HasColumnName("toptier");

                    b.Property<string>("linktransfermarket")
                        .HasColumnType("text")
                        .HasColumnName("linktransfermarket");

                    b.HasKey("Id");

                    b.ToTable("competicoes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CompeticaoTopTierUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("CompeticaoId")
                        .HasColumnType("integer")
                        .HasColumnName("competicaoid");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("competicoestoptierusuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CriterioNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acaoid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision")
                        .HasColumnName("peso");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("criterionotas");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CronometroPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("InicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicioutc");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("SegundosAcumulados")
                        .HasColumnType("integer")
                        .HasColumnName("segundosacumulados");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cronometrospartida");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CuriosidadeTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("DataBusca")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("databusca");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("curiosidadestime");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Escalacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("FaseEscalacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faseescalacao");

                    b.Property<bool>("IsTimeCasa")
                        .HasColumnType("boolean")
                        .HasColumnName("istimecasa");

                    b.Property<int?>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<string>("Posicao")
                        .HasColumnType("text")
                        .HasColumnName("posicao");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaox");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaoy");

                    b.Property<bool>("Titular")
                        .HasColumnType("boolean")
                        .HasColumnName("titular");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("escalacoes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.EstatisticaJogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Assistencias")
                        .HasColumnType("integer")
                        .HasColumnName("assistencias");

                    b.Property<int>("Bloqueios")
                        .HasColumnType("integer")
                        .HasColumnName("bloqueios");

                    b.Property<int>("CartoesAmarelos")
                        .HasColumnType("integer")
                        .HasColumnName("cartoesamarelos");

                    b.Property<int>("CartoesVermelhos")
                        .HasColumnType("integer")
                        .HasColumnName("cartoesvermelhos");

                    b.Property<int>("Defesas")
                        .HasColumnType("integer")
                        .HasColumnName("defesas");

                    b.Property<int>("Desarmes")
                        .HasColumnType("integer")
                        .HasColumnName("desarmes");

                    b.Property<int>("DriblesCertos")
                        .HasColumnType("integer")
                        .HasColumnName("driblescertos");

                    b.Property<int>("DriblesSofridos")
                        .HasColumnType("integer")
                        .HasColumnName("driblessofridos");

                    b.Property<int>("DriblesTentados")
                        .HasColumnType("integer")
                        .HasColumnName("driblestentados");

                    b.Property<int>("DuelosTotal")
                        .HasColumnType("integer")
                        .HasColumnName("duelostotal");

                    b.Property<int>("DuelosVencidos")
                        .HasColumnType("integer")
                        .HasColumnName("duelosvencidos");

                    b.Property<int>("FaltasCometidas")
                        .HasColumnType("integer")
                        .HasColumnName("faltascometidas");

                    b.Property<int>("FaltasSofridas")
                        .HasColumnType("integer")
                        .HasColumnName("faltassofridas");

                    b.Property<int>("FinalizacoesNoGol")
                        .HasColumnType("integer")
                        .HasColumnName("finalizacoesnogol");

                    b.Property<int>("FinalizacoesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("finalizacoestotal");

                    b.Property<int>("Gols")
                        .HasColumnType("integer")
                        .HasColumnName("gols");

                    b.Property<int>("GolsSofridos")
                        .HasColumnType("integer")
                        .HasColumnName("golssofridos");

                    b.Property<int>("Interceptacoes")
                        .HasColumnType("integer")
                        .HasColumnName("interceptacoes");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int?>("Minutos")
                        .HasColumnType("integer")
                        .HasColumnName("minutos");

                    b.Property<int>("Offsides")
                        .HasColumnType("integer")
                        .HasColumnName("offsides");

                    b.Property<int>("PassesChave")
                        .HasColumnType("integer")
                        .HasColumnName("passeschave");

                    b.Property<int>("PassesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("passestotal");

                    b.Property<int>("PenaltiCometido")
                        .HasColumnType("integer")
                        .HasColumnName("penalticometido");

                    b.Property<int>("PenaltiDefendido")
                        .HasColumnType("integer")
                        .HasColumnName("penaltidefendido");

                    b.Property<int>("PenaltiPerdido")
                        .HasColumnType("integer")
                        .HasColumnName("penaltiperdido");

                    b.Property<int>("PenaltiSofrido")
                        .HasColumnType("integer")
                        .HasColumnName("penaltisofrido");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.ToTable("estatisticasjogador");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.FaseTatica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chave");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("MinutoInicio")
                        .HasColumnType("integer")
                        .HasColumnName("minutoinicio");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("fasestaticas");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Formacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("formacoes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atualizado")
                        .HasColumnType("boolean")
                        .HasColumnName("atualizado");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datanascimento");

                    b.Property<DateTime?>("DtAlt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtalt");

                    b.Property<DateTime>("DtInc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinc");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("fotourl");

                    b.Property<long?>("IdApi")
                        .HasColumnType("bigint")
                        .HasColumnName("idapi");

                    b.Property<int?>("IdadeTransfermarkt")
                        .HasColumnType("integer")
                        .HasColumnName("idadetransfermarkt");

                    b.Property<int?>("NacionalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("nacionalidadeid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int?>("NumeroCamisa")
                        .HasColumnType("integer")
                        .HasColumnName("numerocamisa");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posicao");

                    b.Property<string>("PrimeiroNome")
                        .HasColumnType("text")
                        .HasColumnName("primeironome");

                    b.Property<int?>("SelecaoId")
                        .HasColumnType("integer")
                        .HasColumnName("selecaoid");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.Property<string>("UltimoNome")
                        .HasColumnType("text")
                        .HasColumnName("ultimonome");

                    b.Property<string>("linktransfermarket")
                        .HasColumnType("text")
                        .HasColumnName("linktransfermarket");

                    b.HasKey("Id");

                    b.HasIndex("NacionalidadeId");

                    b.HasIndex("SelecaoId");

                    b.HasIndex("TimeId");

                    b.ToTable("jogadores");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("Analisado")
                        .HasColumnType("integer")
                        .HasColumnName("analisado");

                    b.Property<string>("Arbitro")
                        .HasColumnType("text")
                        .HasColumnName("arbitro");

                    b.Property<int>("Atualizado")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado");

                    b.Property<int>("CompeticaoId")
                        .HasColumnType("integer")
                        .HasColumnName("competicaoid");

                    b.Property<string>("CorCamisaCasa")
                        .HasColumnType("text")
                        .HasColumnName("corcamisacasa");

                    b.Property<string>("CorCamisaVisitante")
                        .HasColumnType("text")
                        .HasColumnName("corcamisavisitante");

                    b.Property<string>("CorNumeroCasa")
                        .HasColumnType("text")
                        .HasColumnName("cornumerocasa");

                    b.Property<string>("CorNumeroVisitante")
                        .HasColumnType("text")
                        .HasColumnName("cornumerovisitante");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Estadio")
                        .HasColumnType("text")
                        .HasColumnName("estadio");

                    b.Property<string>("EstatisticasJson")
                        .HasColumnType("text")
                        .HasColumnName("estatisticasjson");

                    b.Property<int>("EventKey")
                        .HasColumnType("integer")
                        .HasColumnName("eventkey");

                    b.Property<int?>("FormacaoCasaId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaocasaid");

                    b.Property<int?>("FormacaoVisitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaovisitanteid");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("fotourl");

                    b.Property<string>("Grupo")
                        .HasColumnType("text")
                        .HasColumnName("grupo");

                    b.Property<string>("LinkDetalhes")
                        .HasColumnType("text")
                        .HasColumnName("linkdetalhes");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int>("PartidaApiId")
                        .HasColumnType("integer")
                        .HasColumnName("partidaapiid");

                    b.Property<int?>("PenaltisCasa")
                        .HasColumnType("integer")
                        .HasColumnName("penaltiscasa");

                    b.Property<int?>("PenaltisVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("penaltisvisitante");

                    b.Property<int?>("PlacarCasa")
                        .HasColumnType("integer")
                        .HasColumnName("placarcasa");

                    b.Property<int?>("PlacarVisitante")
                        .HasColumnType("integer")
                        .HasColumnName("placarvisitante");

                    b.Property<int>("Rodada")
                        .HasColumnType("integer")
                        .HasColumnName("rodada");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Temporada")
                        .HasColumnType("integer")
                        .HasColumnName("temporada");

                    b.Property<int>("TimeCasaId")
                        .HasColumnType("integer")
                        .HasColumnName("timecasaid");

                    b.Property<int>("TimeVisitanteId")
                        .HasColumnType("integer")
                        .HasColumnName("timevisitanteid");

                    b.HasKey("Id");

                    b.HasIndex("CompeticaoId");

                    b.HasIndex("FormacaoCasaId");

                    b.HasIndex("FormacaoVisitanteId");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("jogos");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.JogoAnalisadoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("jogosanalisadosusuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<bool>("IsAutomatica")
                        .HasColumnType("boolean")
                        .HasColumnName("isautomatica");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<double?>("NotaManual")
                        .HasColumnType("double precision")
                        .HasColumnName("notamanual");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuarioid");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Notadetalhe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("AcaoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acaoid");

                    b.Property<string>("AcaoLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acaolabel");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer")
                        .HasColumnName("notaid");

                    b.Property<double>("Peso")
                        .HasColumnType("double precision")
                        .HasColumnName("peso");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("notadetalhes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.PosicaoFormacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("FormacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaoid");

                    b.Property<string>("NomePosicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nomeposicao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("PosicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("posicaoid");

                    b.Property<double>("PosicaoX")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaox");

                    b.Property<double>("PosicaoY")
                        .HasColumnType("double precision")
                        .HasColumnName("posicaoy");

                    b.HasKey("Id");

                    b.HasIndex("FormacaoId");

                    b.ToTable("posicoesformacao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("text")
                        .HasColumnName("backgroundurl");

                    b.Property<string>("CamisaUrl")
                        .HasColumnType("text")
                        .HasColumnName("camisaurl");

                    b.Property<string>("CamisaVisitanteUrl")
                        .HasColumnType("text")
                        .HasColumnName("camisavisitanteurl");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<string>("CorPrincipal")
                        .HasColumnType("text")
                        .HasColumnName("corprincipal");

                    b.Property<string>("CorSecundaria")
                        .HasColumnType("text")
                        .HasColumnName("corsecundaria");

                    b.Property<bool>("EhSelecao")
                        .HasColumnType("boolean")
                        .HasColumnName("ehselecao");

                    b.Property<string>("EscudoUrl")
                        .HasColumnType("text")
                        .HasColumnName("escudourl");

                    b.Property<int>("FormacaoPadraoId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaopadraoid");

                    b.Property<int>("IdApi")
                        .HasColumnType("integer")
                        .HasColumnName("idapi");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("linktransfermarket")
                        .HasColumnType("text")
                        .HasColumnName("linktransfermarket");

                    b.HasKey("Id");

                    b.HasIndex("FormacaoPadraoId");

                    b.ToTable("times");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.TimeEscalacaoPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("FormacaoId")
                        .HasColumnType("integer")
                        .HasColumnName("formacaoid");

                    b.Property<int?>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posicao");

                    b.Property<int>("PosicaoId")
                        .HasColumnType("integer")
                        .HasColumnName("posicaoid");

                    b.Property<int>("PosicaoX")
                        .HasColumnType("integer")
                        .HasColumnName("posicaox");

                    b.Property<int>("PosicaoY")
                        .HasColumnType("integer")
                        .HasColumnName("posicaoy");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.Property<bool>("Titular")
                        .HasColumnType("boolean")
                        .HasColumnName("titular");

                    b.HasKey("Id");

                    b.HasIndex("FormacaoId");

                    b.HasIndex("JogadorId");

                    b.HasIndex("TimeId");

                    b.ToTable("timeescalacaopadrao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.TransfermarktSincronizacaoLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uuid")
                        .HasColumnName("cicloid");

                    b.Property<string>("CompeticaoNome")
                        .HasColumnType("text")
                        .HasColumnName("competicaonome");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<string>("JogoDescricao")
                        .HasColumnType("text")
                        .HasColumnName("jogodescricao");

                    b.Property<string>("TimeNome")
                        .HasColumnType("text")
                        .HasColumnName("timenome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("transfermarktsincronizacaologs");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Treinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datanascimento");

                    b.Property<DateTime?>("DtAlt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtalt");

                    b.Property<DateTime>("DtInc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinc");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("fotourl");

                    b.Property<long?>("IdApi")
                        .HasColumnType("bigint")
                        .HasColumnName("idapi");

                    b.Property<string>("LinkOgol")
                        .HasColumnType("text")
                        .HasColumnName("linkogol");

                    b.Property<int?>("NacionalidadeId")
                        .HasColumnType("integer")
                        .HasColumnName("nacionalidadeid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.HasKey("Id");

                    b.HasIndex("NacionalidadeId");

                    b.HasIndex("TimeId");

                    b.ToTable("treinadores");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.TreinadorHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtfim");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dtinicio");

                    b.Property<int>("TimeId")
                        .HasColumnType("integer")
                        .HasColumnName("timeid");

                    b.Property<int>("TreinadorId")
                        .HasColumnType("integer")
                        .HasColumnName("treinadorid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("TreinadorId");

                    b.ToTable("treinadoreshistorico");
                });

            modelBuilder.Entity("Gol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("Contra")
                        .HasColumnType("boolean")
                        .HasColumnName("contra");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int?>("JogoId1")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid1");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.HasIndex("JogoId");

                    b.HasIndex("JogoId1");

                    b.ToTable("gols", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrencystamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalizedname");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnetroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claimtype");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claimvalue");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("providerkey");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("providerdisplayname");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("roleid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("loginprovider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("Nacionalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("nacionalidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Argentina"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "França"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Alemanha"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Itália"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Espanha"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Portugal"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Uruguai"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Chile"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Paraguai"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Bolívia"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Peru"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Equador"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Colômbia"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Venezuela"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Guiana"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Suriname"
                        });
                });

            modelBuilder.Entity("Substituicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsTimeCasa")
                        .HasColumnType("boolean")
                        .HasColumnName("istimecasa");

                    b.Property<int>("JogadorEntrouId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorentroud");

                    b.Property<int?>("JogadorSaiuId")
                        .HasColumnType("integer")
                        .HasColumnName("jogadorsaiuid");

                    b.Property<int>("JogoId")
                        .HasColumnType("integer")
                        .HasColumnName("jogoid");

                    b.Property<int>("Minuto")
                        .HasColumnType("integer")
                        .HasColumnName("minuto");

                    b.HasKey("Id");

                    b.HasIndex("JogadorEntrouId");

                    b.HasIndex("JogadorSaiuId");

                    b.HasIndex("JogoId");

                    b.ToTable("substituicoes", (string)null);
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.AnotacaoTime", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Time");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Assistencia", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Cartao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", null)
                        .WithMany("Cartoes")
                        .HasForeignKey("JogoId1");

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CompeticaoTopTierUsuario", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Competicao", "Competicao")
                        .WithMany()
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CriterioNota", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CronometroPartida", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.CuriosidadeTime", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Escalacao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId");

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany("Escalacoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.EstatisticaJogador", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.FaseTatica", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogador", b =>
                {
                    b.HasOne("Nacionalidade", "Nacionalidade")
                        .WithMany("Jogadores")
                        .HasForeignKey("NacionalidadeId");

                    b.HasOne("ControleFutebolWeb.Models.Time", "Selecao")
                        .WithMany()
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nacionalidade");

                    b.Navigation("Selecao");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogo", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Competicao", "Competicao")
                        .WithMany("Jogos")
                        .HasForeignKey("CompeticaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Formacao", "FormacaoCasa")
                        .WithMany()
                        .HasForeignKey("FormacaoCasaId");

                    b.HasOne("ControleFutebolWeb.Models.Formacao", "FormacaoVisitante")
                        .WithMany()
                        .HasForeignKey("FormacaoVisitanteId");

                    b.HasOne("ControleFutebolWeb.Models.Time", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Time", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicao");

                    b.Navigation("FormacaoCasa");

                    b.Navigation("FormacaoVisitante");

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeVisitante");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.JogoAnalisadoUsuario", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Nota", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Notadetalhe", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Nota", "Nota")
                        .WithMany("Detalhes")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.PosicaoFormacao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Formacao", "Formacao")
                        .WithMany("Posicoes")
                        .HasForeignKey("FormacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formacao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Time", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Formacao", "FormacaoPadrao")
                        .WithMany()
                        .HasForeignKey("FormacaoPadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormacaoPadrao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.TimeEscalacaoPadrao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Formacao", "Formacao")
                        .WithMany()
                        .HasForeignKey("FormacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId");

                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany("TimeEscalacaoPadrao")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formacao");

                    b.Navigation("Jogador");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Treinador", b =>
                {
                    b.HasOne("Nacionalidade", "Nacionalidade")
                        .WithMany()
                        .HasForeignKey("NacionalidadeId");

                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nacionalidade");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.TreinadorHistorico", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Treinador", "Treinador")
                        .WithMany("Historicos")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("Gol", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogo", null)
                        .WithMany("Gols")
                        .HasForeignKey("JogoId1");

                    b.Navigation("Jogador");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Substituicao", b =>
                {
                    b.HasOne("ControleFutebolWeb.Models.Jogador", "JogadorEntrou")
                        .WithMany()
                        .HasForeignKey("JogadorEntrouId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFutebolWeb.Models.Jogador", "JogadorSaiu")
                        .WithMany()
                        .HasForeignKey("JogadorSaiuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ControleFutebolWeb.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JogadorEntrou");

                    b.Navigation("JogadorSaiu");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Competicao", b =>
                {
                    b.Navigation("Jogos");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Formacao", b =>
                {
                    b.Navigation("Posicoes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Jogo", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Escalacoes");

                    b.Navigation("Gols");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Nota", b =>
                {
                    b.Navigation("Detalhes");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Time", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("TimeEscalacaoPadrao");
                });

            modelBuilder.Entity("ControleFutebolWeb.Models.Treinador", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("Nacionalidade", b =>
                {
                    b.Navigation("Jogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
